services:  
  portainer:
    image: portainer/portainer-ce
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    restart: always
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      ensg_sdi:
        ipv4_address: 172.24.0.22

  dozzle:
    image: amir20/dozzle:latest
    container_name: ${COMPOSE_PROJECT_NAME}_dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_BASE=/logs
    networks:
      ensg_sdi:
        ipv4_address: 172.24.0.30

  filebrowser:
    image: filebrowser/filebrowser
    container_name: ${COMPOSE_PROJECT_NAME}_filebrowser
    restart: unless-stopped
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - FB_BASE_URL=/data
      # The list of avalable options can be found here : https://filebrowser.org/cli/filebrowser#options.
    expose:
      - "8080" 
    volumes:
      - filebrowser_data:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config
      - geoserver-data:/srv/geoserver-data
      - geoserver-injected-data:/srv/geoserver-injected
      - geoserver-settings:/srv/geoserver-settings
    networks:
      ensg_sdi:
        ipv4_address: 172.24.0.40  

  postgis:
    image: postgis/postgis:16-3.4
    container_name: ${COMPOSE_PROJECT_NAME}_postgis
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ensgdb
      POSTGRES_USER: ensgadmin
      POSTGRES_PASSWORD: ensgpassword
      ALLOW_IP_RANGE: 0.0.0.0/0
      FORCE_SSL: FALSE
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
    networks:
      ensg_sdi:
        ipv4_address: 172.24.0.10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    restart: unless-stopped
    environment:
      # Identifiants de démo (à changer en vrai)
      - PGADMIN_DEFAULT_EMAIL=admin@ensg.eu
      - PGADMIN_DEFAULT_PASSWORD=ensgadminadmin
      # Hosting sous sous-répertoire (/pgadmin)
      - SCRIPT_NAME=/pgadmin
    networks:
      ensg_sdi:
        ipv4_address: 172.24.0.50

  # -> Geo server
  geoserver:
    container_name: ${COMPOSE_PROJECT_NAME}_geoserver
    image: kartoza/geoserver:${GS_VERSION}
    expose:
      - "8080"
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - ROOT_WEBAPP_REDIRECT=${ROOT_WEBAPP_REDIRECT}
      - TOMCAT_EXTRAS=${TOMCAT_EXTRAS}
      - SAMPLE_DATA=${SAMPLE_DATA}
      # Extensions set to be installed
      - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
      - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
      - PROXY_BASE_URL=/geoserver
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - geoserver-injected-data:/opt/geoserver/data_dir/injected
      - geoserver-settings:/settings
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u ${GEOSERVER_ADMIN_USER}:'${GEOSERVER_ADMIN_PASSWORD}' http://localhost:8080/geoserver/rest/about/version.xml"
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      ensg_sdi:
        ipv4_address: 172.24.10.3

  #
  # Project reverse proxy
  nginx-proxy:
    image: ${COMPOSE_PROJECT_NAME}_proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - postgis
      - pgadmin
      - filebrowser
      - geoserver
    build:
      context: ./config/nginx-proxy
    environment:
      - DHPARAM_GENERATION=false
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=ensg-sdi.docker
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    profiles:
      - proxyfied
    networks:
      ensg_sdi:
        ipv4_address: 172.24.0.2

  #  -> MapStore2
  mapstore2:
    image: geosolutionsit/mapstore2:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mapstore2
    restart: unless-stopped
    expose: 
      - "8080"
    networks:
      ensg_sdi:
        ipv4_address: 172.24.10.5

  # -> Homepage
  homepage:
    image: gethomepage/homepage:latest
    container_name: ${COMPOSE_PROJECT_NAME}_homepage
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=ensg-sdi.docker
      - PUID=1000
      - PGID=1000
    networks:
      ensg_sdi:
        ipv4_address: 172.24.10.6

volumes:
  geoserver-data:
  geoserver-injected-data:
  geoserver-settings:
  portainer_data:
  postgis_data:
  filebrowser_data:
  filebrowser_database:
  filebrowser_config:

networks:
  ensg_sdi:
    external: true